# Generated by Django 6.0.8 on 2026-09-03 00:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("api", "0001_initial"),
        ("api", "0002_apikey_delete_roleapikey_and_more"),
        ("api", "0003_alter_apikey_revoked_reason"),
        ("api", "0004_apikey_revoked_at"),
        ("api", "0005_alter_apikey_revoked_reason"),
        ("api", "0006_apiactivitylog"),
        ("api", "0007_alter_apiactivitylog_options"),
        ("api", "0008_apiactivitylog_indexes"),
    ]

    initial = True

    dependencies = [
        ("srl", "0036_alter_categories_game_alter_games_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "scope_capabilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not revoked"),
                            ("user", "Revoked by owner"),
                            ("permission_revoked", "Permission revoked"),
                            ("admin", "Revoked by admin"),
                            ("banned", "Banned by admin"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "scope_games",
                    models.ManyToManyField(
                        blank=True, related_name="scoping_keys", to="srl.games"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ("-created",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user"], name="api_apikey_user_id_f5d68d_idx"),
                    models.Index(
                        fields=["last_used"], name="api_apikey_last_us_e612bf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("session", "Session"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="anonymous",
                        max_length=16,
                    ),
                ),
                (
                    "key_label_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=512)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("target_app", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("change_summary", models.JSONField(blank=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="api.apikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Activity Entry",
                "verbose_name_plural": "API Activity",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="api_actl_user_cr_idx"
                    ),
                    models.Index(
                        fields=["api_key", "-created_at"], name="api_actl_key_cr_idx"
                    ),
                    models.Index(
                        fields=["target_app", "target_model", "target_id"],
                        name="api_actl_target_idx",
                    ),
                    models.Index(fields=["status_code"], name="api_actl_status_idx"),
                    models.Index(fields=["method"], name="api_actl_method_idx"),
                    models.Index(
                        fields=["-created_at"], name="apiactivitylog_created_idx"
                    ),
                    models.Index(
                        fields=["target_app", "target_model", "-created_at"],
                        name="apiactivitylog_target_idx",
                    ),
                ],
            },
        ),
    ]
