# Generated by Django 6.0.4 on 2026-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_apikey_delete_roleapikey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not revoked"),
                    ("user", "Revoked by owner"),
                    ("permission_revoked", "Permission revoked"),
                    ("admin", "Revoked by admin"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
