# Generated by Django 6.0.4 on 2026-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_apikey_revoked_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="revoked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
