# Generated by Django 6.0.4 on 2026-05-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_apikey_revoked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not revoked"),
                    ("user", "Revoked by owner"),
                    ("permission_revoked", "Permission revoked"),
                    ("admin", "Revoked by admin"),
                    ("banned", "Banned by admin"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
