# Generated by Django 6.0.4 on 2026-05-14 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_apikey_revoked_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("session", "Session"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="anonymous",
                        max_length=16,
                    ),
                ),
                (
                    "key_label_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=512)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("target_app", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("change_summary", models.JSONField(blank=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="api.apikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API activity entry",
                "verbose_name_plural": "API activity",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="api_actl_user_cr_idx"
                    ),
                    models.Index(
                        fields=["api_key", "-created_at"], name="api_actl_key_cr_idx"
                    ),
                    models.Index(
                        fields=["target_app", "target_model", "target_id"],
                        name="api_actl_target_idx",
                    ),
                    models.Index(fields=["status_code"], name="api_actl_status_idx"),
                    models.Index(fields=["method"], name="api_actl_method_idx"),
                ],
            },
        ),
    ]
