# Generated by Django 6.0.4 on 2026-05-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_apiactivitylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiactivitylog",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "API Activity Entry",
                "verbose_name_plural": "API Activity",
            },
        ),
    ]
