# Generated by Django 6.0.4 on 2026-04-10 01:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import django_resized.forms
import srl.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "encrypted_api_key",
                    models.TextField(
                        blank=True,
                        help_text="Fernet-encrypted Speedrun.com API key. Never expose in API responses.",
                        null=True,
                        verbose_name="Encrypted SRC API Key",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Markdown-formatted biography. Max 1000 characters.",
                        max_length=1000,
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
                (
                    "therun_gg",
                    models.TextField(
                        blank=True,
                        help_text="therun.gg account.",
                        max_length=30,
                        null=True,
                        verbose_name="therun.gg Profile",
                    ),
                ),
                (
                    "short_bio",
                    models.CharField(
                        blank=True,
                        help_text="Brief bio displayed on profile. Max 100 characters. Emojis allowed.",
                        max_length=100,
                        null=True,
                        verbose_name="Short Bio",
                    ),
                ),
                (
                    "gradient_1",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for name gradient (#RRGGBB). Primary/solid color.",
                        max_length=7,
                        null=True,
                        verbose_name="Gradient Color 1",
                    ),
                ),
                (
                    "gradient_2",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for name gradient (#RRGGBB). Requires gradient_1.",
                        max_length=7,
                        null=True,
                        verbose_name="Gradient Color 2",
                    ),
                ),
                (
                    "gradient_3",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for name gradient (#RRGGBB). Requires gradient_2.",
                        max_length=7,
                        null=True,
                        verbose_name="Gradient Color 3",
                    ),
                ),
                (
                    "profile_bg",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        help_text="Profile background image. Max 2560x1440. Max 10MB.",
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[2560, 1440],
                        upload_to="profile_bg",
                        validators=[srl.models.base.validate_profile_bg],
                        verbose_name="Profile Background",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
