# Generated by Django 6.0.5 on 2026-05-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userdataexport"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userdataexport",
            new_name="accounts_us_user_id_1ff512_idx",
            old_name="accounts_us_user_id_56e1b1_idx",
        ),
        migrations.RenameIndex(
            model_name="userdataexport",
            new_name="accounts_us_user_id_888ff8_idx",
            old_name="accounts_us_user_id_b9c2a4_idx",
        ),
    ]
