# Generated by Django 6.0.6 on 2026-06-06 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_backfill_email_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                help_text="Last time this user row changed.",
            ),
            preserve_default=False,
        ),
    ]
