# Generated by Django 6.0.6 on 2026-06-10 23:22

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def ensure_no_duplicate_emails(
    apps,
    schema_editor,
) -> None:
    """Abort loudly (listing offenders) if case-insensitive duplicate emails exist.

    The constraint below cannot be added over duplicate data; duplicates mean two
    accounts share an email and must be resolved by a human, not a migration.
    """
    User = apps.get_model("accounts", "CustomUser")
    duplicates = (
        User.objects.exclude(email="")
        .annotate(email_ci=Lower("email"))
        .values("email_ci")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("-n")
    )
    rows = list(duplicates[:20])
    if rows:
        offenders = ", ".join(f"{row['email_ci']} (x{row['n']})" for row in rows)
        raise RuntimeError(
            "Cannot add the unique-email constraint while duplicate emails exist: "
            f"{offenders}. Resolve the duplicates manually, then re-run migrate."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_updated_at"),
    ]

    operations = [
        migrations.RunPython(
            ensure_no_duplicate_emails,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                Lower("email"),
                condition=~models.Q(email=""),
                name="unique_user_email_ci",
            ),
        ),
    ]
