# Generated by Django 6.0.4 on 2026-05-22 20:33

from django.db import migrations

OLD_KEYS = ("user_data_export_ready", "user_data_export_failed")
NEW_KEY = "user_data_export"


def consolidate_forward(apps, schema_editor):
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")

    by_user: dict[int, list[bool]] = {}
    rows = NotificationPreference.objects.filter(type__in=OLD_KEYS).values_list(
        "user_id",
        "enabled",
    )
    for user_id, enabled in rows:
        by_user.setdefault(user_id, []).append(enabled)

    for user_id, flags in by_user.items():
        merged_enabled = all(flags)
        NotificationPreference.objects.update_or_create(
            user_id=user_id,
            type=NEW_KEY,
            defaults={"enabled": merged_enabled},
        )

    NotificationPreference.objects.filter(type__in=OLD_KEYS).delete()


def consolidate_reverse(apps, schema_editor):
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")

    rows = list(
        NotificationPreference.objects.filter(type=NEW_KEY).values(
            "user_id", "enabled"
        ),
    )
    for row in rows:
        for old_key in OLD_KEYS:
            NotificationPreference.objects.update_or_create(
                user_id=row["user_id"],
                type=old_key,
                defaults={"enabled": row["enabled"]},
            )

    NotificationPreference.objects.filter(type=NEW_KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(consolidate_forward, consolidate_reverse),
    ]
