# Generated by Django 6.0.8 on 2026-09-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("guides", "0001_initial"),
        ("guides", "0002_alter_guides_game"),
        ("guides", "0003_guides_owner"),
        ("guides", "0004_alter_guides_slug_guides_unique_guide_slug_per_game"),
    ]

    initial = True

    dependencies = [
        ("srl", "0001_initial"),
        ("srl", "0036_alter_categories_game_alter_games_slug_and_more"),
        ("srl", "0063_backfill_required_methods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tag Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(max_length=100, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Guide Title")),
                ("slug", models.SlugField(max_length=200, verbose_name="Slug")),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief description of what this guide covers.",
                        max_length=500,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full guide content; markdown is allowed.",
                        verbose_name="Guide Content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At:"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At:"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="srl.games",
                        verbose_name="Associated Game",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="guides.tags", verbose_name="Tags"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this guide.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_guides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guides",
                "ordering": ["-created_at", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "slug"), name="unique_guide_slug_per_game"
                    )
                ],
            },
        ),
    ]
