# Generated by Django 6.0.4 on 2026-04-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        ('srl', '0036_alter_categories_game_alter_games_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='srl.games', verbose_name='Associated Game'),
        ),
    ]
