# Generated by Django 6.0.4 on 2026-04-22 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_alter_guides_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guides",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this guide.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_guides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
