# Generated by Django 6.0.2 on 2026-02-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0020_variablevalues_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='runs',
            name='idx_runs_game_cat_sub_level',
        ),
        migrations.AlterField(
            model_name='players',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='appear_on_main',
            field=models.BooleanField(default=False, help_text='When unchecked, runs with this variable value will NOT appear on the main page, even if the parent category is enabled.', verbose_name='Appear on Main Page'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['game', 'category', 'level'], name='idx_runs_game_cat_level'),
        ),
        migrations.RemoveField(
            model_name='runs',
            name='subcategory',
        ),
    ]
