# Generated by Django 6.0.3 on 2026-03-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0024_add_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='is_claimed',
        ),
    ]
