# Generated by Django 6.0.3 on 2026-03-20 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0025_remove_players_is_claimed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='Players who are moderators for this game on thps.run. If a player is a moderator here but not on SRC, thps.run takes precedence.', related_name='moderated_games', to='srl.players', verbose_name='Moderators'),
        ),
        migrations.CreateModel(
            name='SRCCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(help_text='Fernet-encrypted SRC API key. Never expose this value in any API response.', verbose_name='Encrypted SRC API Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='src_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SRC Credential',
                'verbose_name_plural': 'SRC Credentials',
            },
        ),
    ]
