# Generated by Django 6.0.3 on 2026-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0026_games_moderators_srccredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='discord',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='Discord'),
        ),
        migrations.AlterField(
            model_name='srccredential',
            name='encrypted_api_key',
            field=models.TextField(help_text='Encrypted SRC API key. Never expose this value in any API response.', verbose_name='Encrypted SRC API Key'),
        ),
    ]
