# Generated by Django 6.0.3 on 2026-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0027_players_discord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='discord',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Discord'),
        ),
    ]
