# Generated by Django 6.0.3 on 2026-03-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0028_alter_players_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='joined',
            field=models.DateField(blank=True, help_text="Date of the player's earliest verified speedrun.", null=True, verbose_name='Joined'),
        ),
    ]
