# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0029_players_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="rules",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="Rules"
            ),
        ),
    ]
