# Generated by Django 6.0.3 on 2026-04-01 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0030_games_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRCSyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verify', 'Verify'), ('reject', 'Reject'), ('change_players', 'Change Players')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payload', models.JSONField(help_text='The JSON body to send to the SRC API.')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('last_error', models.TextField(blank=True, default='', help_text='Error details from the most recent failed attempt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='src_sync_tasks', to='srl.players')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='srl.runs')),
            ],
            options={
                'verbose_name': 'SRC Sync Task',
                'verbose_name_plural': 'SRC Sync Tasks',
                'indexes': [models.Index(fields=['status'], name='idx_srcsync_status'), models.Index(fields=['run', 'status'], name='idx_srcsync_run_status')],
            },
        ),
    ]
