# Generated by Django 6.0.3 on 2026-04-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0031_src_sync_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='players',
            field=models.PositiveIntegerField(default=1, help_text='Number of players this category accepts.', verbose_name='Number of Players'),
        ),
    ]
