# Generated by Django 6.0.3 on 2026-04-04 01:30

import django.db.models.deletion
import django_resized.forms
import srl.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0032_add_players_to_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Note: Images must be at least 64px in size, must be a square (height and width must match), and the max filesize is 3MB.', keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to='awards', validators=[srl.models.base.validate_image], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_runs', to='srl.players', verbose_name='Approver'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['game', 'category', 'level', 'obsolete'], name='idx_runs_game_cat_level_obs'),
        ),
    ]
