# Generated by Django 6.0.4 on 2026-04-10 02:15

import django_resized.forms
import srl.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0034_migrate_pfps_to_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycodes',
            name='flag',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Custom flag image for countries not in the frontend flag library. Must have 1.5 aspect ratio (e.g. 72x48). Max 3MB.', keep_meta=True, null=True, quality=-1, scale=None, size=[72, 48], upload_to='flags', validators=[srl.models.base.validate_flag_image], verbose_name='Custom Flag'),
        ),
        migrations.DeleteModel(
            name='SRCCredential',
        ),
    ]
