# Generated by Django 6.0.4 on 2026-04-19 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0035_countrycodes_flag_delete_srccredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.games', verbose_name='Linked Game'),
        ),
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Abbreviation/Slug'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.games', verbose_name='Linked Game'),
        ),
        migrations.AlterField(
            model_name='nowstreaming',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.games', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='players',
            name='countrycode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.countrycodes', verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='players',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runs',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_runs', to='srl.players', verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.levels', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.platforms', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='srcsynctask',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='src_sync_tasks', to='srl.players'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='cat',
            field=models.ForeignKey(blank=True, help_text='If not set, the variable  is seen as a "global" variable for the scope you choose below. For example: a "global" variable set for "Only IL Runs" will make it a GLOBAL variable for IL speedruns.', null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.games', verbose_name='Linked Game'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='level',
            field=models.ForeignKey(blank=True, help_text='If "scope" is set to "single-level", then a level must be associated. Otherwise, keep null.', null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.levels', verbose_name='Associated Level'),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='srl.variables', verbose_name='Linked Variable'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['vid_status'], name='idx_runs_vid_status'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['obsolete'], name='idx_runs_obsolete'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['date'], name='idx_runs_date'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['vid_status', 'obsolete', 'place'], name='idx_runs_vstatus_obs_place'),
        ),
    ]
