# Generated by Django 6.0.4 on 2026-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0038_variables_defaulttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phpsessid_encrypted", models.TextField(blank=True, default="")),
                ("csrf_token", models.CharField(blank=True, default="", max_length=64)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("refreshing", "Refreshing"),
                            ("locked_out", "Locked Out"),
                        ],
                        default="expired",
                        max_length=20,
                    ),
                ),
                (
                    "last_refresh_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "v2_enabled_override",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Runtime override for SRC_V2_ENABLED. None inherits the env value.",
                        null=True,
                    ),
                ),
                (
                    "consecutive_refresh_failures",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Counter of refresh_bot_session() failures since last successful refresh. Used to trip the circuit breaker at >= 3.",
                    ),
                ),
                (
                    "disabled_by_circuit_breaker",
                    models.BooleanField(
                        default=False,
                        help_text="True when v2 was auto-disabled by trip_circuit_breaker(). Distinguishes 'admin paused' from 'system tripped'.",
                    ),
                ),
                (
                    "last_severe_error_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent breaker trip.",
                        null=True,
                    ),
                ),
                (
                    "last_severe_error_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ErrorCategory value of most recent breaker trip.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Session",
                "verbose_name_plural": "Bot Session",
            },
        ),
    ]
