# Generated by Django 6.0.4 on 2026-05-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0039_botsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="srcsynctask",
            name="error_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Categorized failure reason for the most recent attempt; blank when status is synced or no attempts have failed.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="srcsynctask",
            name="action",
            field=models.CharField(
                choices=[
                    ("verify", "Verify"),
                    ("reject", "Reject"),
                    ("change_players", "Change Players"),
                    ("edit_run", "Edit Run"),
                ],
                max_length=20,
            ),
        ),
    ]
