# Generated by Django 6.0.4 on 2026-05-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0041_reconciliation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reconciliationitem",
            new_name="srl_reconci_job_id_ca8e88_idx",
            old_name="srl_recon_item_job_phase_idx",
        ),
        migrations.AlterField(
            model_name="reconciliationjob",
            name="phase",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("P1", "Phase 1: Surface Level"),
                    ("P2", "Phase 2: Obsolete Backfill"),
                    ("P3", "Phase 3: Recompute Leaderboards"),
                ],
                default="PENDING",
                max_length=8,
            ),
        ),
    ]
