# Generated by Django 6.0.4 on 2026-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "srl",
            "0042_rename_srl_recon_item_job_phase_idx_srl_reconci_job_id_ca8e88_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reconciliationjob",
            name="scope",
            field=models.CharField(
                choices=[
                    ("RUN", "Run"),
                    ("LEADERBOARD", "Leaderboard"),
                    ("GAME", "Game"),
                    ("SERIES", "Series"),
                ],
                max_length=16,
            ),
        ),
    ]
