# Generated by Django 6.0.4 on 2026-05-16 16:00

import django.contrib.postgres.fields
from django.db import migrations, models

import srl.models.base


def forward(apps, schema_editor):
    METHOD_REWRITE = {
        "realtime": "rta",
        "realtime_noloads": "lrt",
        "ingame": "igt",
    }

    Games = apps.get_model("srl", "Games")
    Categories = apps.get_model("srl", "Categories")
    Variables = apps.get_model("srl", "Variables")
    VariableValues = apps.get_model("srl", "VariableValues")
    Runs = apps.get_model("srl", "Runs")

    for old, new in METHOD_REWRITE.items():
        Games.objects.filter(defaulttime=old).update(defaulttime=new)
        Games.objects.filter(idefaulttime=old).update(idefaulttime=new)
        Categories.objects.filter(defaulttime=old).update(defaulttime=new)
        Variables.objects.filter(defaulttime=old).update(defaulttime=new)
        VariableValues.objects.filter(defaulttime=old).update(defaulttime=new)
        Runs.objects.filter(primary_method_override=old).update(
            primary_method_override=new,
        )

    from django.db import connection

    with connection.cursor() as cursor:
        for old, new in METHOD_REWRITE.items():
            cursor.execute(
                "UPDATE srl_games SET allowed_methods_fg = array_replace("
                "allowed_methods_fg, %s, %s) WHERE %s = ANY(allowed_methods_fg)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_games SET allowed_methods_il = array_replace("
                "allowed_methods_il, %s, %s) WHERE %s = ANY(allowed_methods_il)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_categories SET allowed_methods = array_replace("
                "allowed_methods, %s, %s) WHERE %s = ANY(allowed_methods)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_variables SET allowed_methods = array_replace("
                "allowed_methods, %s, %s) WHERE %s = ANY(allowed_methods)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_variablevalues SET allowed_methods = array_replace("
                "allowed_methods, %s, %s) WHERE %s = ANY(allowed_methods)",
                [old, new, old],
            )


def reverse(apps, schema_editor):
    METHOD_REWRITE = {
        "rta": "realtime",
        "lrt": "realtime_noloads",
        "igt": "ingame",
    }

    Games = apps.get_model("srl", "Games")
    Categories = apps.get_model("srl", "Categories")
    Variables = apps.get_model("srl", "Variables")
    VariableValues = apps.get_model("srl", "VariableValues")
    Runs = apps.get_model("srl", "Runs")

    for old, new in METHOD_REWRITE.items():
        Games.objects.filter(defaulttime=old).update(defaulttime=new)
        Games.objects.filter(idefaulttime=old).update(idefaulttime=new)
        Categories.objects.filter(defaulttime=old).update(defaulttime=new)
        Variables.objects.filter(defaulttime=old).update(defaulttime=new)
        VariableValues.objects.filter(defaulttime=old).update(defaulttime=new)
        Runs.objects.filter(primary_method_override=old).update(
            primary_method_override=new,
        )

    from django.db import connection

    with connection.cursor() as cursor:
        for old, new in METHOD_REWRITE.items():
            cursor.execute(
                "UPDATE srl_games SET allowed_methods_fg = array_replace("
                "allowed_methods_fg, %s, %s) WHERE %s = ANY(allowed_methods_fg)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_games SET allowed_methods_il = array_replace("
                "allowed_methods_il, %s, %s) WHERE %s = ANY(allowed_methods_il)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_categories SET allowed_methods = array_replace("
                "allowed_methods, %s, %s) WHERE %s = ANY(allowed_methods)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_variables SET allowed_methods = array_replace("
                "allowed_methods, %s, %s) WHERE %s = ANY(allowed_methods)",
                [old, new, old],
            )
            cursor.execute(
                "UPDATE srl_variablevalues SET allowed_methods = array_replace("
                "allowed_methods, %s, %s) WHERE %s = ANY(allowed_methods)",
                [old, new, old],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0044_categories_allowed_methods_games_allowed_methods_fg_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
        migrations.AlterField(
            model_name="games",
            name="defaulttime",
            field=models.CharField(
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default="rta",
                max_length=20,
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="idefaulttime",
            field=models.CharField(
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default="rta",
                help_text=(
                    "Sometimes leaderboards have one timing standard for full game "
                    "speedruns and another standard for ILs. This setting lets you change the "
                    "game-specific IL timing method.<br />NOTE: This defaults to RTA upon a game "
                    "being created and must be set manually."
                ),
                max_length=20,
                verbose_name="ILs Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="allowed_methods_fg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                default=srl.models.base.all_methods_default,
                help_text=(
                    "Timing methods allowed for full-game runs of this game. Must include "
                    "defaulttime. Subset chain enforces narrowing down the inheritance hierarchy."
                ),
                verbose_name="Allowed FG Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="allowed_methods_il",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                default=srl.models.base.all_methods_default,
                help_text=(
                    "Timing methods allowed for individual-level runs of this game. Must include "
                    "idefaulttime."
                ),
                verbose_name="Allowed IL Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="defaulttime",
            field=models.CharField(
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text=(
                    "When not set, the category's associated game's timing method(s) are used. "
                    "When used, the timing method for the ENTIRE category will take take precedence "
                    "over what is set for the category's associated game. ALL requests will use this to "
                    "determine what timing method is used for the category."
                ),
                max_length=20,
                null=True,
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="allowed_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text=(
                    "When set, narrows the timing methods allowed for runs in this category. "
                    "Must be a non-empty subset of the parent game's allowed methods. Null inherits "
                    "from the game."
                ),
                null=True,
                verbose_name="Allowed Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="variables",
            name="defaulttime",
            field=models.CharField(
                blank=True,
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text=(
                    "When not set, the variable inherits its category's timing method (or the game's "
                    "if the category does not set one). When set, this takes precedence over both the "
                    "category and game timing for any run that includes this variable. "
                    "Precedence: Variable > Category > Game."
                ),
                max_length=20,
                null=True,
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="variables",
            name="allowed_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text=(
                    "When set, narrows the timing methods allowed for runs that include this variable. "
                    "Must be a non-empty subset of the parent (category/game). Null inherits."
                ),
                null=True,
                verbose_name="Allowed Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="variablevalues",
            name="defaulttime",
            field=models.CharField(
                blank=True,
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text=(
                    "When not set, the value inherits its variable's timing method (or further up "
                    "the chain). When set, this is the most specific override and takes precedence "
                    "over the parent variable, the category, and the game. "
                    "Precedence: VariableValue > Variable > Category > Game."
                ),
                max_length=20,
                null=True,
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="variablevalues",
            name="allowed_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text=(
                    "When set, narrows the timing methods allowed for runs with this value. "
                    "Must be a non-empty subset of the parent variable's effective allowed methods. "
                    "Null inherits."
                ),
                null=True,
                verbose_name="Allowed Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="runs",
            name="primary_method_override",
            field=models.CharField(
                blank=True,
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text=(
                    "Per-run override of the resolved primary timing method. Used for legacy runs "
                    "that lack data for the game's current primary. Writable by moderators only."
                ),
                max_length=20,
                null=True,
                verbose_name="Primary Method Override",
            ),
        ),
    ]
