# Generated by Django 6.0.4 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0045_shorten_timing_method_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runs",
            name="primary_method_override",
        ),
    ]
