# Generated by Django 6.0.4 on 2026-05-17 03:50

import django.contrib.postgres.fields
from django.db import migrations, models

import srl.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0046_remove_runs_primary_method_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="verbose_recalc_log",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, every per-board recalculation writes a RECALC_BOARD entry to this game's audit log. Off by default - high-volume events.",
                verbose_name="Verbose Recalc Logging",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="allowed_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text="When set, narrows the timing methods allowed for runs in this category. Must be a non-empty subset of the parent game's allowed methods. Null inherits from a higher level.",
                null=True,
                verbose_name="Allowed Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="defaulttime",
            field=models.CharField(
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text="When not set, the category's associated game's timing method(s) are used. When used, the timing method for the ENTIRE category will take take precedence over what is set for the category's associated game. ALL requests will use this to determine what timing method is used for the category.",
                null=True,
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="allowed_methods_fg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                default=srl.models.base.all_methods_default,
                help_text="Timing methods allowed for full-game runs of this game. Must include defaulttime.",
                verbose_name="Allowed FG Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="defaulttime",
            field=models.CharField(
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default="rta",
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="idefaulttime",
            field=models.CharField(
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default="rta",
                help_text="Sometimes leaderboards have one timing standard for full game speedruns and another standard for ILs. This setting lets you change the game-specific IL timing method.<br />NOTE: This defaults to RTA upon a game being created and must be set manually.",
                verbose_name="ILs Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="variables",
            name="allowed_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text="When set, narrows the timing methods allowed for runs that include this variable. Must be a non-empty subset of the parent (category/game). Null inherits from a higher level.",
                null=True,
                verbose_name="Allowed Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="variables",
            name="defaulttime",
            field=models.CharField(
                blank=True,
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text="When not set, the variable inherits its category's timing method (or the game's if the category does not set one). When set, this takes precedence over both the category and game timing for any run that includes this variable. Precedence: Variable > Category > Game.",
                null=True,
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="variablevalues",
            name="allowed_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text="When set, narrows the timing methods allowed for runs with this value. Must be a non-empty subset of the parent variable's effective allowed methods. Null inherits from a higher level.",
                null=True,
                verbose_name="Allowed Timing Methods",
            ),
        ),
        migrations.AlterField(
            model_name="variablevalues",
            name="defaulttime",
            field=models.CharField(
                blank=True,
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text="When not set, the value inherits its variable's timing method (or further up the chain). When set, this is the most specific override and takes precedence over the parent variable, the category, and the game. Precedence: VariableValue > Variable > Category > Game.",
                null=True,
                verbose_name="Default Time",
            ),
        ),
    ]
