# Generated by Django 6.0.4 on 2026-05-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0048_alter_series_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="allowed_methods",
            new_name="required_methods",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="allowed_methods_fg",
            new_name="required_methods_fg",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="allowed_methods_il",
            new_name="required_methods_il",
        ),
        migrations.RenameField(
            model_name="variables",
            old_name="allowed_methods",
            new_name="required_methods",
        ),
        migrations.RenameField(
            model_name="variablevalues",
            old_name="allowed_methods",
            new_name="required_methods",
        ),
    ]
