# Generated by Django 6.0.4 on 2026-05-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0049_rename_allowed_methods_categories_required_methods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="ipointsmax",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text='Default is 250; 25O if this game contains the name "Category Extension". This is the maximum total of points an IL speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.',
                verbose_name="IL WR Point Maximum",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="verbose_recalc_log",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, every per-board recalculation writes a `RECALC_BOARD` entry to this game's audit log. Off by default.",
                verbose_name="Verbose Recalc Logging",
            ),
        ),
    ]
