# Generated by Django 6.0.4 on 2026-05-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0050_alter_games_ipointsmax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runs",
            name="review_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Moderator Review Notes"
            ),
        ),
        migrations.AlterField(
            model_name="runs",
            name="vid_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("new", "Unverified"),
                    ("rejected", "Rejected"),
                    ("review", "Under Review"),
                ],
                default="verified",
                help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" or "Rejected" do not appear anywhere on this site.',
                verbose_name="SRC Status",
            ),
        ),
    ]
