# Generated by Django 6.0.4 on 2026-05-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0051_runs_review_notes_alter_runs_vid_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="defaulttime",
            field=models.CharField(
                blank=True,
                choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                default=None,
                help_text=(
                    "When not set, the category's associated game's timing method(s) are used. "
                    "When used, the timing method for the ENTIRE category will take take "
                    "precedence over what is set for the category's associated game. ALL "
                    "requests will use this to determine what timing method is used for the "
                    "category."
                ),
                null=True,
                verbose_name="Default Time",
            ),
        ),
    ]
