# Generated by Django 6.0.5 on 2026-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0052_alter_categories_defaulttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="boxart",
            field=models.CharField(
                help_text="Absolute URL or MEDIA_URL-relative path to the game's box art image.",
                max_length=200,
                verbose_name="Box Art",
            ),
        ),
    ]
