# Generated by Django 6.0.5 on 2026-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0053_alter_games_boxart"),
    ]

    operations = [
        migrations.AddField(
            model_name="runs",
            name="import_issues",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Import Issues",
            ),
        ),
        migrations.AddField(
            model_name="runs",
            name="has_import_issues",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Has Import Issues",
            ),
        ),
    ]
