# Generated by Django 6.0.5 on 2026-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0054_runs_import_issues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runs",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
