# Generated by Django 6.0.6 on 2026-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0055_runs_created_at_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reconciliationjob",
            name="pending_children",
        ),
        migrations.RemoveField(
            model_name="reconciliationjob",
            name="failure_count",
        ),
    ]
