# Generated by Django 6.0.6 on 2026-06-10 19:22


from django.db import migrations, models


def close_duplicate_open_history(
    apps,
    schema_editor,
) -> None:
    """Close all but the newest open history row per run so the constraint can apply."""
    RunHistory = apps.get_model("srl", "RunHistory")

    kept_start_by_run: dict = {}
    to_close: list = []
    open_rows = (
        RunHistory.objects.filter(end_date__isnull=True)
        .order_by("run_id", "-start_date", "-created_at", "-pk")
        .iterator()
    )
    for row in open_rows:
        kept_start = kept_start_by_run.get(row.run_id)
        if kept_start is None:
            kept_start_by_run[row.run_id] = row.start_date
            continue
        row.end_date = max(kept_start, row.start_date)
        row.end_reason = "recalculation"
        to_close.append(row)

    if to_close:
        RunHistory.objects.bulk_update(
            to_close,
            ["end_date", "end_reason"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0056_retire_reconciliation_engine"),
    ]

    operations = [
        migrations.RunPython(
            close_duplicate_open_history,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="runhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(end_date__isnull=True),
                fields=("run",),
                name="unique_open_runhistory_per_run",
            ),
        ),
    ]
