# Generated by Django 6.0.6 on 2026-07-03 22:45

from django.db import migrations
from django.db.models import Q
from django.utils.text import slugify


def backfill_category_slugs(apps, schema_editor):
    """Populate empty slugs on Categories left blank by a destructive game rebuild.

    Categories are imported via ``sync_categories`` (and, historically, before the model
    gained a slug-on-save hook) without an explicit slug. The original one-time backfill
    (migration 0005) only covered rows that existed then, so any game rebuilt afterward
    came back with empty category slugs, breaking the frontend leaderboard lookup. This
    re-runs the same slugify logic, scoped to the rows still missing a slug.
    """
    symbol_exemptions = {
        "+": "-plus",
        "&": "-and",
        "/": "-",
    }

    Categories = apps.get_model("srl", "Categories")
    for category in Categories.objects.filter(Q(slug="") | Q(slug__isnull=True)):
        slug = category.name
        for old, new in symbol_exemptions.items():
            slug = slug.replace(old, new)

        category.slug = slugify(slug)
        category.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0057_runhistory_unique_open_row"),
    ]

    operations = [
        migrations.RunPython(
            backfill_category_slugs,
            migrations.RunPython.noop,
        ),
    ]
