# Generated by Django 6.0.6 on 2026-07-04 12:45

from django.db import migrations
from django.db.models import Q
from django.utils.text import slugify

# Mirror of srl.models.base.SLUG_SYMBOL_EXEMPTIONS, inlined so this historical migration
# stays self-contained (the original backfill, 0005, inlined the same map).
SYMBOL_EXEMPTIONS = {
    "+": "-plus",
    "&": "-and",
    "/": "-",
}

# Models whose slug is derived from ``name``. Games is intentionally excluded: its slugs
# are deliberate abbreviations (e.g. "thps12"), not slugified names, and it was likewise
# left out of migration 0005.
SLUGIFIED_MODELS = [
    "Categories",
    "Levels",
    "Platforms",
    "Variables",
    "VariableValues",
]


def _make_slug(name):
    """Recompute a slug applying the symbol exemptions (see migration 0005)."""
    for old, new in SYMBOL_EXEMPTIONS.items():
        name = name.replace(old, new)
    return slugify(name)


def backfill_symbol_slugs(apps, schema_editor):
    """Repair slugs of symbol-bearing names left wrong by a destructive rebuild.

    A bare ``slugify`` drops ``+``/``&``/``/``, so re-imported rows such as "NG+" became
    "ng" (colliding with sibling "NG") instead of "ng-plus". Only rows whose name contains
    one of those symbols are considered, and only those whose recomputed slug actually
    differs are touched, so correct and custom slugs are left untouched.
    """
    symbol_filter = (
        Q(name__contains="+") | Q(name__contains="&") | Q(name__contains="/")
    )
    for model_name in SLUGIFIED_MODELS:
        Model = apps.get_model("srl", model_name)
        for obj in Model.objects.filter(symbol_filter):
            new_slug = _make_slug(obj.name)
            if obj.slug != new_slug:
                obj.slug = new_slug
                obj.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0058_backfill_category_slugs"),
    ]

    operations = [
        migrations.RunPython(
            backfill_symbol_slugs,
            migrations.RunPython.noop,
        ),
    ]
