# Generated by Django 6.0.6 on 2026-07-05 14:32

from django.db import migrations, models
from django.db.models.functions import Lower, Upper


def _lowercase_actions(apps, schema_editor):
    """Convert existing ReconciliationItem.action values to lowercase.

    The six ReconAction values are simple case folds (e.g. SKIPPED_LOCAL_WINS ->
    skipped_local_wins), so a blanket LOWER() covers every historical row.
    """
    ReconciliationItem = apps.get_model("srl", "ReconciliationItem")
    ReconciliationItem.objects.update(action=Lower("action"))


def _uppercase_actions(apps, schema_editor):
    """Reverse: restore ReconciliationItem.action values to uppercase."""
    ReconciliationItem = apps.get_model("srl", "ReconciliationItem")
    ReconciliationItem.objects.update(action=Upper("action"))


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0059_backfill_symbol_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationjob",
            name="mode",
            field=models.CharField(
                choices=[
                    ("recent", "Recent verified runs"),
                    ("full_game", "All full-game (main) runs"),
                    ("il", "All individual-level runs"),
                ],
                default="recent",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationjob",
            name="run_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reconciliationitem",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("skipped_local_wins", "Skipped (local wins)"),
                    ("skipped_no_change", "Skipped (no change)"),
                    ("missing_on_src", "Missing on SRC"),
                    ("failed", "Failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(_lowercase_actions, _uppercase_actions),
    ]
