# Generated by Django 6.0.7 on 2026-07-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0060_reconciliationjob_mode_reconciliationjob_run_limit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="required_methods",
            new_name="allowed_methods",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="required_methods_fg",
            new_name="allowed_methods_fg",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="required_methods_il",
            new_name="allowed_methods_il",
        ),
        migrations.RenameField(
            model_name="variables",
            old_name="required_methods",
            new_name="allowed_methods",
        ),
        migrations.RenameField(
            model_name="variablevalues",
            old_name="required_methods",
            new_name="allowed_methods",
        ),
    ]
