# Generated by Django 6.0.7 on 2026-07-23 03:43

import django.contrib.postgres.fields
from django.db import migrations, models

import srl.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0061_rename_required_methods_categories_allowed_methods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="required_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text="When set, the subset of allowed methods a run MUST supply (the rest are optional). Must include the primary. Null inherits.",
                null=True,
                verbose_name="Required Timing Methods",
            ),
        ),
        migrations.AddField(
            model_name="games",
            name="required_methods_fg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                default=srl.models.base.all_methods_default,
                help_text="Timing methods a full-game run MUST supply. Must be a subset of the allowed methods and include defaulttime. Allowed methods not listed here are optional.",
                verbose_name="Required FG Timing Methods",
            ),
        ),
        migrations.AddField(
            model_name="games",
            name="required_methods_il",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                default=srl.models.base.all_methods_default,
                help_text="Timing methods an IL run MUST supply. Must be a subset of the allowed methods and include idefaulttime. Allowed methods not listed here are optional.",
                verbose_name="Required IL Timing Methods",
            ),
        ),
        migrations.AddField(
            model_name="variables",
            name="required_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text="When set, the subset of allowed methods a run MUST supply (the rest are optional). Must include the primary. Null inherits.",
                null=True,
                verbose_name="Required Timing Methods",
            ),
        ),
        migrations.AddField(
            model_name="variablevalues",
            name="required_methods",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("rta", "RTA"), ("lrt", "LRT"), ("igt", "IGT")],
                    max_length=20,
                ),
                blank=True,
                default=None,
                help_text="When set, the subset of allowed methods a run MUST supply (the rest are optional). Must include the primary. Null inherits.",
                null=True,
                verbose_name="Required Timing Methods",
            ),
        ),
    ]
