# Generated by Django 6.0.7 on 2026-07-23 03:43

from django.db import migrations


def backfill_required(apps, schema_editor):
    """Set required_methods == allowed_methods for every existing row."""
    Games = apps.get_model("srl", "Games")
    for g in Games.objects.all():
        g.required_methods_fg = list(g.allowed_methods_fg)
        g.required_methods_il = list(g.allowed_methods_il)
        g.save(update_fields=["required_methods_fg", "required_methods_il"])
    for model_name in ("Categories", "Variables", "VariableValues"):
        Model = apps.get_model("srl", model_name)
        for obj in Model.objects.exclude(allowed_methods__isnull=True):
            obj.required_methods = list(obj.allowed_methods)
            obj.save(update_fields=["required_methods"])


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0062_categories_required_methods_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_required, migrations.RunPython.noop),
    ]
