# Generated by Django 6.0.3 on 2026-04-08 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. "Discord", "Twitter", "YouTube"', max_length=50, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.IntegerField(default=0, help_text='Controls display order. order=0 items sort alphabetically as a fallback. Items with order>=1 sort first in ascending order.', verbose_name='Sort Order')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Display Label')),
                ('url', models.CharField(blank=True, help_text='Optional link target. Leave blank for group headers.', max_length=255, null=True, verbose_name='URL')),
                ('order', models.IntegerField(default=0, help_text='Controls display order. order=0 items sort alphabetically as a fallback. Items with order>=1 sort first in ascending order.', verbose_name='Sort Order')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nav.navitem', verbose_name='Parent Item')),
            ],
            options={
                'verbose_name': 'Nav Item',
                'verbose_name_plural': 'Nav Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
