# Generated by Django 6.0.4 on 2026-05-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameauditevent",
            name="target_id",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
